### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by roeintense**
Proposing addition of new botbuilder-storage-postgres to packages per @benbrown 's suggestion.

### CODE REVIEW

**Comment by garypretty** [comment]
@roeintense @szul The allowance for the howdyai bits was a special acceptance, given that this is an established repo and Microsoft now owning howdy.  I would prefer, is possible, to accept the postgres storage provider into the community repo.  I really would prefer not to establish a pattern of linking to other repos, as we then don't have any control of the updating of content.

**Comment by szul** [comment]
@roeintense Curious as to your objections to moving the storage component into the `botbuilder-community-js` repository as an additional folder item under the `libraries` folder?

**Comment by roeintense** [comment]
> As per @garypretty's request of @benbrown for the howyai items, since this is a link pointing to an external repo, would you mind adding a link on your README back to the community project?

@szul  link added per https://github.com/TDAmeritrade/botbuilder-storage-postgres/issues/5

**Comment by roeintense** [comment]
> @roeintense Curious as to your objections to moving the storage component into the `botbuilder-community-js` repository as an additional folder item under the `libraries` folder?

I'm not sure what this means exactly. Are you requesting ownership of the repo entirely? Seems like there's still some storming and norming happening around how all this should come together. (I.e. This adapter was built using the `botbuilder-storage-mongodb` repo has a model. Why isn't that nor the Redis botbuilder-storage modules part of the libraries?) Just trying to understand. Thanks.

**Comment by garypretty** [comment]
@roeintense The libs that you mention, such as botbuilder-storage-mongodb, have been developed by others in their own repos, as you have done. This is fantastic that this work has taken place.  We as a project have created the Bot Builder Community to try and have a consistent place for this kind of thing, but it is totally up to individual contributors as to if they add their code to the Community repo or not.  To be clear, we are not requesting ownership of your repo, but if you wanted to submit the specific piece of code into our repo we would gratefully accept it.

For example, the adapters, recognizers that @szul, I and others all had in our own repos originally were moved here when we created the community project.

Hope that helps explain. Thanks again for reaching out with this.

**Comment by szul** [comment]
We would like to expand the community repo to include other projects. We can add you as the codeowner in the codeowner file, so you can review changes.

It's okay if you want to keep your own repo, and not add this to the community repo. @garypretty is just saying that we want to avoid linking out to other repos, and filling our README with links out. Ben's was an exception.

We have not reached out to other repo owners, and asked them to contribute to this repo, but they are more than welcome to.

**Comment by roeintense** [comment]
@szul @garypretty I feel like I understand much better now. I'll skip a PR at the moment since I'm still getting my feet wet with this stuff, but let's keep that door open for future collaboration.

**Comment by garypretty** [comment]
@roeintense Thanks and no problem!

**Comment by szul** [comment]
@roeintense @garypretty Good to close this PR?

**Pull request closed without merging**
