### PR TITLE
Add basic CI/CD using Azure Pipelines

### PR DESCRIPTION
**Pull request by iMicknl**
- [Fail on error /w test statistics](https://github.com/iMicknl/botbuilder-community-js/runs/185650749)
- Run npm audit
- Run eslint
- Run mocha tests

v.future:
- I haven't enabled the `lerna publish` yet, since I am not able to test it. @szul. Could you implement this later. Guess this has less priority. 
- Enable branch protection rule for master. -> Require status checks to pass before merging. (and maybe also the required reviews?)
- Currently the test-ci is present in all package.jsons... Would be great to have it just in the root package, however couldn't get the xunit reporter working from the root package.

### CODE REVIEW

**Comment by iMicknl** [comment]
@szul  / @garypretty could you enable Azure DevOps on this repository, so it will use this definition for this PR? I have tested it on my fork, but would like to see it in action here also.

**Comment by szul** [comment]
@iMicknl @garypretty I think this repo is enabled for Azure Pipelines now. Is there something you need me to do/check on that end?

**Comment by iMicknl** [comment]
@szul have you created a new project in the `BotBuilder-Community` organisation? I can only see https://dev.azure.com/BotBuilder-Community/dotnet. When this repository is linked to a project in the organisation, it should be working automatically I thought.

**Comment by szul** [comment]
@iMicknl Yes, there's a: https://dev.azure.com/BotBuilder-Community/js/

Pretty sure I have it linked via the settings here on GitHub. @garypretty any insight?

**Comment by iMicknl** [comment]
@szul could you try creating a new Build Pipeline [here](https://dev.azure.com/BotBuilder-Community/js/_build).

**Comment by szul** [comment]
@iMicknl Set up and built. I think we're good?

**Pull request merged**
