### PR TITLE
Add MongoDB Storage Adapter

### PR DESCRIPTION
**Pull request by mdrichardson**
I took [a StackOverflow issue](https://stackoverflow.com/questions/57639411/how-to-use-mongodb-locally-and-directline-js-for-state-management-in-bot-framewo/57664920) where a user wanted to use MongoDB for BotState. Since I wrote up an adapter for it, I figured I may as well submit it here.

This should be considered a personal submission, and not a Microsoft one.

### CODE REVIEW

**Comment by szul** [comment]
@mdrichardson This is great. Can you take a look at the v1 branch of this repo? We’re renaming the storage package to specifically be for Azure Table storage since that’s all that’s in it. Moving forward we’re doing separate packages: storage-azure-table, storage-mongodb, etc. Do you think you can do that and then do a PR against the v1 branch? We’re moving towards a v1 with a full CI/CD pipeline, ESLint, etc.

**Comment by szul** [comment]
This’ll also eliminate some of the confusion with the Microsoft code.

**Comment by mdrichardson** [comment]
@szul Will do. This is low on my priority list, so it may be a few days...just FYI.

**Comment by szul** [comment]
@mdrichardson No problem. If I finish some of the stuff I’m working on, I might PR to your PR to break it out. Then we can merge with master and back port to v1 before adding the linting, etc. The contribution is much appreciated!

**Comment by szul** [comment]
I’ll publish the package on NPM tomorrow. Thanks!

**Pull request merged**
