### PR TITLE
Add TSLint and editorconfig

### LINKED ISSUE #21: Add TSLint to project
Suggested by @iMicknl to clean up the code, and make it more uniform. Would align us with the Bot Framework team's usage.

### PR DESCRIPTION
**Pull request by iMicknl**
Add the same TSLint configuration and editorconfig as the [botbuilder-js](https://github.com/Microsoft/botbuilder-js) project. This adds a new private npm package to the root of the project to run `tslint` over all packages.

As we are not using lerna (yet?) to manage all different libraries, this extra npm package can look like some overhead, however I think it is better than adding tslint to every library itself.

Fixes #21

### CODE REVIEW

**Comment by iMicknl** [comment]
_Seperate PR will fix all warnings._

**Comment by iMicknl** [comment]
@szul I don't have that many experience with Lerna, just see it used a lot to manage a multi package structure in a single Git repo. Lerna won't cause any problems for this PR.

What is the status of implementing Azure Piplines / DevOps for @BotBuilderCommunity repo's?

**Comment by szul** [comment]
@iMicknl I haven't had a chance to look into it. @garypretty Have you done this for the dotnet side? Do you know if we're all able to work together on build/deploy, or are they separate accounts/domains?

**Comment by iMicknl** [comment]
@szul @garypretty any update on this? Would love to have this merged in, even before we have the Azure Pipelines / DevOps set up.

**Comment by szul** [comment]
I can merge this, but it leaves us with the errors, no? I was waiting for #26 to be complete. Is that still active, or is it complete?

**Comment by iMicknl** [comment]
@szul I will take some time to finish #26 and I will have to break it up in multiple PR's. It are just too much changes to process by hand. At the moment TSLint will only throw warnings.

Any progress on the Azure Pipelines set up? For running tests, tslint and build. (maybe using Lerna?)

**Comment by szul** [comment]
I had Lerna working but rolled it back. I can re-implement. Not sure if @garypretty created an org for Azure Pipelines yet. Pretty sure we can do it without sharing a tenant.

**Comment by szul** [comment]
@iMicknl Wonder if we should do TSLint per library/package and tackle it package-by-package. Then refactor to a repo-based TSLint when it’s all done...

That’ll prevent a repo full of warnings, but allow us to work a better pace.

**Comment by szul** [comment]
@iMicknl I'm wrapping up something, but afterwards, I'm going to merge this in.

**Comment by iMicknl** [comment]
@szul cool! Sorry I didn't respond yet, however I guess a TSLint per package is quite overkill at the moment and will make it also hard to run it in a CI/CD build.

**Comment by szul** [comment]
@iMicknl On holiday break for a week or so, so I'll be merging this one in soon, and then adding Lerna as well. Might make some mods after merging in order to eliminate warnings until we have the coding style fully implemented. Then I'll try to tackle Azure Pipelines to replace Travis-CI.

**Comment by szul** [comment]
Going to tackle this in two steps. I'm pulling it into a branch on my fork, so I can modify the tslint implementation to be per package for now. Then I'll merge this PR. Then I'll send in a PR to merge my modifications. This will set the repo up with tslint on a per package basis, so builds aren't riddled with warnings. Once the packages are retrofitted with the tslint, we can pull it out to the base package as a single instance.

**Pull request merged**
