### PR TITLE
Add new adapters to the adapters list

### PR DESCRIPTION
**Pull request by benbrown**
These adapters were created aspart of Botkit, but are compatible with BotBuilder too!

### CODE REVIEW

**Comment by szul** [comment]
@garypretty I leave this in your hands. Not sure your philosophy of the README linking out to external repos. I defer to your preference. We can pretty up the README organization if we have to.

**Comment by garypretty** [comment]
@szul @benbrown @tomlm Apologies for the delay in coming back on this - I have been getting ready to head out on vacation to Florida so I have been stacked.  I am now 35,000 feet up on my way, so have a little time! :)  

I think as long as we call out somewhere that these repos are external to the community repo itself, then I quite like the idea of including them.  Especially as they have come from a reputable / established repo (i.e. this won't be something I advocate for lot's of random external repos).

@benbrown Could we ask that a reciprocal link back to our adapters be placed in the HowdyAI repo readme?

**Comment by benbrown** [comment]
Absolutely! Done -

Here:
https://github.com/howdyai/botkit/tree/master/packages/botkit#platform-support

and here:
https://github.com/howdyai/botkit/blob/master/packages/docs/core.md#the-botkit-controller

**Comment by szul** [comment]
@benbrown See if you're okay with the README edit. Feel free to adjust and do another PR. Going to merge this now.

**Comment by benbrown** [comment]
All good! FYI "Howdy.ai" was acquired by Microsoft and I (and the Botkit project) joined the Bot Framework team.

**Pull request merged**
