### PR TITLE
Put all examples in samples folder in root

### PR DESCRIPTION
**Pull request by CaptainLazarus**
#123 Any mistakes or all set?

### CODE REVIEW

**Comment by iMicknl** [comment]
@szul should we reference to the examples in README like dotnet repo is doing?

**Comment by szul** [comment]
@iMicknl Definitely.

**Comment by CaptainLazarus** [comment]
on it

**Comment by CaptainLazarus** [comment]
Where exactly should package.json be pointing?

**Comment by szul** [comment]
Package.json should just be updated so the main entry point is the same as the file name that is being used as an example especially if you rename those index.js

**Comment by szul** [comment]
None of the samples are TypeScript so JS is fine. The thing where the path needs to be adjusted is the require statements in the sample. Some of the internal pointers probably should point to the packages themselves (via NPM install)

**Comment by szul** [comment]
@CaptainLazarus Once done: I’ll push this to my repo when I get the chance to validate the chatbots that need keys. Then I’ll merge it. Thanks a lot!

**Comment by CaptainLazarus** [comment]
Thanks :)

**Pull request merged**
