### PR TITLE
[Core] Add CustomWebAdapter 

### PR DESCRIPTION
**Pull request by iMicknl**
DRY

@szul as discussed, it would be good to separate some code that is used multiple times. One of the approaches could be to create a new adapter that can be used as the base for all our Custom Web Adapters. 

What do you think?

### CODE REVIEW

**Comment by szul** [comment]
@iMicknl This works for me. Should this be `util` or something like `core` (naming-wise)? I tend to look at `tools` and `util` as packages that would have helper functions, but since this is a class implementing these details is `util` fine, or is there a different naming convention we should use?

Just asking. Naming things is hard 😕

**Comment by iMicknl** [comment]
@szul I am not sure about the naming either. botbuilder-core sounded a bit to much like the official core packages. However in the scope, `@botbulder-community/core` it sounds better than util indeed.

**Comment by szul** [comment]
Sounds good. Let's go with `@botbuildercommunity/core` then. We'll use this for when we need interfaces, abstract class, etc. that are common among packages.

**Comment by arafattehsin** [comment]
Hi guys! 

+1 for the name! Just to align with other repos, we can name it:

@BotBuilderCommunity/**botbuilder-community-core**

Thoughts?

**Comment by szul** [comment]
Our naming convention has generally been that the package name is the folder name minus the prefixed “botbuilder-“.

So if the folder is “botbuilder-core” then the package is “@botbuildercommunity/core” removing the folder prefix and stashing it in our org scope.

@iMicknl and I have discussed in the past either renaming all folders sub of “libraries” to use “botbuildercommunity-“ as the prefix instead of “botbuilder-“ or simply removing the prefix altogether since the repo is “botbuilder-community-js”.

I don’t think we ever decided. This would be a good PR to do that in though since we’re having the discussion again.

**Comment by szul** [comment]
I reopened issue #68 in response to this.

**Comment by iMicknl** [comment]
@szul what do you think about the name CustomWebAdapter? Possibly we coul name it `WebAdapter`, `CustomHttpAdapter` or `HttpAdapter`? 
@arafattehsin

**Comment by szul** [comment]
I'm fine with either, but "Web" rolls off the tongue better than "Http", in my opinion.

**Comment by iMicknl** [comment]
@szul please do not merge yet. I need to add some tests and test it with all packages.

**Comment by iMicknl** [comment]
Closing in favor of #149.

**Pull request closed without merging**
