### PR TITLE
Add ESLint to root

### PR DESCRIPTION
**Pull request by iMicknl**
- Implemented ESLint
- Ignored all current packages, except for one.

I think it would be good to implement ESLint + a ruleset, to have better code quality and consistency across all libraries. Ruleset is open for discussion. For now I took the default rulesets, which are also being used by `botbuilder-js`. 

Would be great to have this one running (with errors) in CI/CD for the 1.0 release.

### CODE REVIEW

**Comment by szul** [comment]
How close is this to the `tslint` we initially tried? I dropped the `tslint` to the individual package level on some packages, and have been slowly working through it.

**Comment by iMicknl** [comment]
[TSLint is on the way to deprecation](https://medium.com/palantir/tslint-in-2019-1a144c2317a9), thus ESLint would be a wiser choice imo. 

What would be the benefit of using it in individual packages? We can ignore the libraries which aren't 100% 'eslintified' yet.

**Comment by szul** [comment]
Fair enough. Did `tslint` not allow for ignored packages from the root? Thought there was a reason we had to do each package separately.

**Comment by iMicknl** [comment]
I am not sure, the TSLint implementation was far from perfect tbh. I will have a look at cleaning it up a bit in the coming days and making the current packages pass the ESLint validation. 

Would be good to have new additions run through the pipeline, to see if we have to change some rules a bit for this project.

**Pull request merged**
