### PR TITLE
[Core] Update all packages to botbuilder 4.8.0 and correct multiple package-lock.json

### PR DESCRIPTION
**Pull request by iMicknl**
- bump all botbuilder related packages to 4.8.0
- npm audit fix
- fix missing @botbuildercommunity/middleware-engine-core in multiple package-lock.json

### CODE REVIEW

**Comment by iMicknl** [comment]
@szul it looks like those changes mean that I have to bump all version numbers (minor) + update change log and that we have to republish? What do you think? :)

**Comment by szul** [comment]
@iMicknl Right. I've seen a couple of tools that can automatic the version increment, but haven't implemented anything yet.

**Comment by szul** [comment]
@iMicknl :shipit:

**Comment by szul** [comment]
@iMicknl Feel free to kill the `develop` branch if you think that's causing confusion. You'll have to re-choose the default branch.

**Comment by iMicknl** [comment]
Merged manually to develop.

**Pull request closed without merging**
