### PR TITLE
Improve CI/CD reporting

### PR DESCRIPTION
**Pull request by iMicknl**
- Change `test-results.xml` to `mocha-test-results.xml`
- Add junit output for ESLint `eslint-test-results.xml` 
- Move npm audit to the end

### CODE REVIEW

**Comment by iMicknl** [comment]
@szul could you enable branch protection of master? 
- Require status checks to pass before merging
- Require branches to be up to date before merging

and preferably also
- Require pull request reviews before merging
+ 
- Include administrators

**Comment by szul** [comment]
@iMicknl Done.

**Comment by szul** [comment]
@iMicknl Might have to role some of the protections back a bit. For example, the `npm audit` fails on Watson, but there's no way to fix the vulnerability until Watson is updated. As such, my PR will sit in the queue until IBM has patched it. Is there a way to the only fail on severe vulnerabilities?

**Comment by iMicknl** [comment]
@szul currently it is set to `--audit-level=moderate`, could you have a look what kind of vulnerabilities still exist? Otherwise we need to lower our security level in CI/CD or just do it as a warning.

**Comment by szul** [comment]
@iMicknl Had to completely switch Watson packages. One of the items had an old reference. This fixed the Watson NLU build, and it's passing. Can you approve the PR real quick, so I can push it through and get the NPM packages up?

**Pull request merged**
