### PR TITLE
WIP: Fix warnings thrown by TSLint

### PR DESCRIPTION
**Pull request by iMicknl**
_work in progress_

### CODE REVIEW

**Comment by szul** [comment]
If #24 is good, and will work well if we move to Azure Pipelines, I'll get this merged as well. It might take me a day or two to get to it.

**Comment by iMicknl** [comment]
It is still work in progress, there are many codestyle things which need to be fixed. Azure Pipelines can already be implemented for the other PR's, since it just treats everything as a warning at the moment.

**Comment by szul** [comment]
@iMicknl So should we close this one, merge #24, modify to make TSLint package-specific instead of in the root of the repo, and then work on each package as we go?

**Comment by iMicknl** [comment]
Closing for now. Many conflicts and outdated.

**Pull request closed without merging**
